### PR TITLE
fix: add liquidity bug

### LINKED ISSUE #1685: Unable to create a new pool
Description:
Luigy, from Discord mentioned that it is not possible to create a new pool.
"when i input one of the tokens the other resets to 0
i think the optimization/calculation to match the other token is just returning 0 every time"

Would be good to have a hotfix for this.

### PR DESCRIPTION
**Pull request by berteotti**
# Summary

Fixes #1685

This PR fixes the add liquidity bug for new tokens

  # To Test

1. Go to create liquidity page
2. Choose token pair with no liquidity
- [ ] Can submit a value for Token A and Token B

### CODE REVIEW

File: src/state/mint/reducer.ts [hunk 1]
```diff
@@ -18,6 +18,7 @@ export default createReducer<MintState>(initialState, builder =>
   builder
     .addCase(resetMintState, () => initialState)
     .addCase(typeInput, (state, { payload: { field, typedValue, noLiquidity } }) => {
+      console.log({ field, typedValue, noLiquidity })
```
Comment (bejzik8) [inline src/state/mint/reducer.ts:21]: Should we remove `console.log` Leo? 😅

**Review by bejzik8 — APPROVED** [review]

File: src/state/mint/reducer.ts (hunk 1 above)
Comment (berteotti) [reply src/state/mint/reducer.ts]: ups, done 😄
